import type { TutorialTour } from '../types'

export const dashboardTour: TutorialTour = {
  id: 'dashboard',
  videoNumber: 9,
  title: 'Management Intelligence Dashboard',
  subtitle: 'From Production Data to Quality Intelligence',
  description: 'Demonstrates the management dashboard with KPIs, NCR trends, repeat issues, and operator performance metrics.',
  estimatedDuration: '3:30',
  steps: [
    {
      id: 'dash-1',
      title: 'Management Dashboard',
      content: 'The ForgeTraceIQ dashboard converts individual production and quality records into management information. This helps identify recurring problems and improvement opportunities.',
      voiceover: 'The ForgeTraceIQ dashboard converts individual production and quality records into management information. This helps identify recurring problems and improvement opportunities.',
      target: 'h1',
      position: 'bottom',
      route: '/dashboard',
      waitForElement: 1000,
    },
    {
      id: 'dash-2',
      title: 'Total NCRs',
      content: 'The total NCR count shows how many quality issues have been recorded. This is the starting point for understanding the scale of quality challenges.',
      voiceover: 'The total NCR count shows how many quality issues have been recorded. This is the starting point for understanding the scale of quality challenges.',
      target: '[class*=kpi]:first-child',
      position: 'right',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-3',
      title: 'Repeat Issues',
      content: 'Repeat issues highlight parts or processes that have recurring quality problems. Three NCRs for Pump Housing with porosity indicates a process that needs engineering attention.',
      voiceover: 'Repeat issues highlight parts or processes that have recurring quality problems. Three NCRs for Pump Housing with porosity indicates a process that needs engineering attention.',
      target: '[class*=repeat]',
      position: 'right',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-4',
      title: 'Failure Trends',
      content: 'Trend charts show how quality issues change over time. An increasing trend in porosity NCRs signals that recent corrective actions may not be effective.',
      voiceover: 'Trend charts show how quality issues change over time. An increasing trend in porosity NCRs signals that recent corrective actions may not be effective.',
      target: '[class*=chart], canvas, svg',
      position: 'left',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-5',
      title: 'Root Cause Analysis',
      content: 'The most common root causes are ranked. If inadequate venting appears at the top, management knows where to focus improvement efforts and capital investment.',
      voiceover: 'The most common root causes are ranked. If inadequate venting appears at the top, management knows where to focus improvement efforts and capital investment.',
      target: '[class*=root]',
      position: 'right',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-6',
      title: 'Operator Performance',
      content: 'Operator performance metrics help identify training needs. Operators with higher NCR rates may need additional training on setup, inspection, or specific processes.',
      voiceover: 'Operator performance metrics help identify training needs. Operators with higher NCR rates may need additional training on setup, inspection, or specific processes.',
      target: '[class*=operator]',
      position: 'right',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-7',
      title: 'Live NCR Feed',
      content: 'The live feed shows recently submitted NCRs in real time. Managers can see quality issues as they happen, not days later in a report.',
      voiceover: 'The live feed shows recently submitted NCRs in real time. Managers can see quality issues as they happen, not days later in a report.',
      target: '[class*=feed]',
      position: 'left',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'dash-8',
      title: 'Data-Driven Decisions',
      content: 'ForgeTraceIQ transforms raw production data into actionable intelligence. Management can now make decisions based on facts rather than anecdote or delayed reports.',
      voiceover: 'ForgeTraceIQ transforms raw production data into actionable intelligence. Management can now make decisions based on facts rather than anecdote or delayed reports.',
      position: 'center',
      route: '/dashboard',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
