import type { TutorialTour } from '../types'

export const endToEndTour: TutorialTour = {
  id: 'end-to-end',
  videoNumber: 10,
  title: 'Complete Manufacturing Story',
  subtitle: 'From Job Creation to Management Intelligence',
  description: 'The flagship tutorial following a complete realistic manufacturing scenario from job creation through setup, production, inspection, failure, NCR, AI analysis, corrective action, and dashboard visibility.',
  estimatedDuration: '8:00',
  steps: [
    {
      id: 'e2e-1',
      title: 'The Manufacturing Day Begins',
      content: 'It is Monday morning. Production Supervisor Sarah Chen logs into ForgeTraceIQ to start the day. Job FTQ-2026-0048 is scheduled: a Pump Housing in Cast Iron GG25.',
      voiceover: 'It is Monday morning. Production Supervisor Sarah Chen logs into ForgeTraceIQ to start the day. Job FTQ-2026-0048 is scheduled: a Pump Housing in Cast Iron GG25.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 5000,
    },
    {
      id: 'e2e-2',
      title: 'Operator Login',
      content: 'Sarah enters her operator ID. Every action she takes will be traceable to her. This is the foundation of accountability in the manufacturing process.',
      voiceover: 'Sarah enters her operator ID. Every action she takes will be traceable to her. This is the foundation of accountability in the manufacturing process.',
      target: 'input',
      position: 'bottom',
      route: '/',
      waitForElement: 500,
    },
    {
      id: 'e2e-3',
      title: 'Job Selection',
      content: 'Sarah selects job FTQ-2026-0048 from the jobs list. She can see the part number, material, and due date at a glance.',
      voiceover: 'Sarah selects job FTQ-2026-0048 from the jobs list. She can see the part number, material, and due date at a glance.',
      target: '[class*=card]',
      position: 'right',
      route: '/job-entry',
      waitForElement: 800,
    },
    {
      id: 'e2e-4',
      title: 'Digital Setup Sheet',
      content: 'The digital setup sheet opens. Sarah reviews the machine settings, tooling requirements, and workholding instructions. Everything she needs is in one place.',
      voiceover: 'The digital setup sheet opens. Sarah reviews the machine settings, tooling requirements, and workholding instructions. Everything she needs is in one place.',
      target: 'h1',
      position: 'bottom',
      route: '/setup-sheet/1',
      waitForElement: 1000,
    },
    {
      id: 'e2e-5',
      title: 'Setup Verification',
      content: 'Sarah follows the setup instructions: machine DMG Mori NLX-2500, tooling Sandvik CNMG 432, 3-jaw chuck 200mm. She verifies each item before starting.',
      voiceover: 'Sarah follows the setup instructions: machine DMG Mori NLX-2500, tooling Sandvik CNMG 432, three-jaw chuck two hundred millimetres. She verifies each item before starting.',
      target: '[class*=setup]',
      position: 'right',
      route: '/setup-sheet/1',
      waitForElement: 500,
    },
    {
      id: 'e2e-6',
      title: 'Production Running',
      content: 'The job is running. Sarah monitors the machining process. The part is a Pump Housing, and the bore diameter must be held to plus 0.02, minus 0.00 millimetres.',
      voiceover: 'The job is running. Sarah monitors the machining process. The part is a Pump Housing, and the bore diameter must be held to very tight tolerances.',
      position: 'center',
      route: '/setup-sheet/1',
      autoAdvance: true,
      autoAdvanceDelay: 4000,
    },
    {
      id: 'e2e-7',
      title: 'First Article Inspection',
      content: 'After machining, Sarah performs first article inspection. She measures five critical dimensions and enters the results into ForgeTraceIQ.',
      voiceover: 'After machining, Sarah performs first article inspection. She measures five critical dimensions and enters the results into ForgeTraceIQ.',
      target: 'h1',
      position: 'bottom',
      route: '/inspection/1',
      waitForElement: 1000,
    },
    {
      id: 'e2e-8',
      title: 'A Problem is Found',
      content: 'The bore diameter measures 150.03 millimetres. The tolerance is plus 0.02, minus 0.00. The part has failed. The system flags this immediately.',
      voiceover: 'The bore diameter measures 150.03 millimetres. The tolerance is plus 0.02, minus zero. The part has failed. The system flags this immediately.',
      target: '[class*=fail]',
      position: 'right',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'e2e-9',
      title: 'Creating the NCR',
      content: 'Sarah creates a Non-Conformance Report. She describes the porosity defect, records the part and job numbers, and classifies the severity as Major.',
      voiceover: 'Sarah creates a Non-Conformance Report. She describes the porosity defect, records the part and job numbers, and classifies the severity as Major.',
      target: 'h1',
      position: 'bottom',
      route: '/ncr',
      waitForElement: 1000,
    },
    {
      id: 'e2e-10',
      title: 'Photographic Evidence',
      content: 'Sarah uploads photographs of the defect. The images clearly show pore clusters in the bore surface.',
      voiceover: 'Sarah uploads photographs of the defect. The images clearly show pore clusters in the bore surface.',
      target: 'input[type=file]',
      position: 'top',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'e2e-11',
      title: 'Root Cause Analysis',
      content: 'Using the five-why method, they identify the root cause: inadequate venting in the mold cavity during pouring, combined with excessive moisture in the sand mix.',
      voiceover: 'Using the five-why method, they identify the root cause: inadequate venting in the mold cavity during pouring, combined with excessive moisture in the sand mix.',
      target: 'textarea',
      position: 'top',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'e2e-12',
      title: 'Corrective Action',
      content: 'Corrective actions are recorded: increase vent holes from four to eight, reduce sand moisture to three point five percent, add risers at the bore location, and re-inspect one hundred percent of the next batch.',
      voiceover: 'Corrective actions are recorded: increase vent holes from four to eight, reduce sand moisture to three point five percent, add risers at the bore location, and re-inspect one hundred percent of the next batch.',
      target: 'textarea',
      position: 'top',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'e2e-13',
      title: 'Foundry NCR & AI Analysis',
      content: 'The foundry team uploads the casting defect photo to ForgeTraceIQ AI analysis. The system identifies porosity with eighty-seven percent confidence.',
      voiceover: 'The foundry team uploads the casting defect photo to ForgeTraceIQ AI analysis. The system identifies porosity with eighty-seven percent confidence.',
      target: '[class*=ai]',
      position: 'left',
      route: '/foundry-ncr',
      waitForElement: 1000,
    },
    {
      id: 'e2e-14',
      title: 'Historical Pattern',
      content: 'The system alerts the team that this is the fourth porosity NCR for Pump Housing. A pattern is emerging that demands engineering attention.',
      voiceover: 'The system alerts the team that this is the fourth porosity NCR for Pump Housing. A pattern is emerging that demands engineering attention.',
      target: '[class*=repeat]',
      position: 'right',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'e2e-15',
      title: 'NCR Status: In Progress',
      content: 'The quality manager marks the NCR as In Progress. The investigation is underway. The foundry supervisor is assigned to implement the corrective actions.',
      voiceover: 'The quality manager marks the NCR as In Progress. The investigation is underway. The foundry supervisor is assigned to implement the corrective actions.',
      target: 'button',
      position: 'top',
      route: '/foundry-ncr-library',
      waitForElement: 1000,
    },
    {
      id: 'e2e-16',
      title: 'NCR Status: Resolved',
      content: 'After corrective actions are verified, the NCR is marked Resolved. The batch is released. The lessons learned are captured for future reference.',
      voiceover: 'After corrective actions are verified, the NCR is marked Resolved. The batch is released. The lessons learned are captured for future reference.',
      target: 'button',
      position: 'top',
      route: '/foundry-ncr-library',
      waitForElement: 500,
    },
    {
      id: 'e2e-17',
      title: 'Management Visibility',
      content: 'The plant manager opens the ForgeTraceIQ dashboard. He sees the total NCR count, open issues, and the Pump Housing porosity trend.',
      voiceover: 'The plant manager opens the ForgeTraceIQ dashboard. He sees the total NCR count, open issues, and the Pump Housing porosity trend.',
      target: '[class*=dashboard]',
      position: 'bottom',
      route: '/dashboard',
      waitForElement: 1000,
    },
    {
      id: 'e2e-18',
      title: 'Data-Driven Decision',
      content: 'Based on the data, the manager approves capital expenditure for improved mold venting and a new sand moisture control system. The decision is backed by evidence.',
      voiceover: 'Based on the data, the manager approves capital expenditure for improved mold venting and a new sand moisture control system. The decision is backed by evidence.',
      target: '[class*=chart]',
      position: 'left',
      route: '/dashboard',
      waitForElement: 500,
    },
    {
      id: 'e2e-19',
      title: 'The Complete Story',
      content: 'ForgeTraceIQ connects manufacturing activity, quality information, non-conformance management, and historical intelligence into one digital workflow.',
      voiceover: 'ForgeTraceIQ connects manufacturing activity, quality information, non-conformance management, and historical intelligence into one digital workflow.',
      position: 'center',
      route: '/dashboard',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
    {
      id: 'e2e-20',
      title: 'From Production Data to Continuous Improvement',
      content: 'From production data, to traceability, to quality intelligence, to continuous improvement. That is the ForgeTraceIQ advantage.',
      voiceover: 'From production data, to traceability, to quality intelligence, to continuous improvement. That is the ForgeTraceIQ advantage.',
      position: 'center',
      route: '/dashboard',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
