import type { TutorialTour } from '../types'

export const failureTour: TutorialTour = {
  id: 'failure',
  videoNumber: 5,
  title: 'When Quality Fails',
  subtitle: 'Managing a Manufacturing Non-Conformance',
  description: 'Demonstrates what happens when inspection fails: creating an NCR, documenting the problem, recording defect details, and capturing corrective actions.',
  estimatedDuration: '4:00',
  steps: [
    {
      id: 'fail-1',
      title: 'Inspection Failure Detected',
      content: 'During inspection of job FTQ-2026-0048, the bore diameter measured 150.03mm against a tolerance of plus 0.02, minus 0.00. The part has failed inspection.',
      voiceover: 'During inspection of job FTQ-2026-0048, the bore diameter measured 150.03 millimetres against a tolerance of plus 0.02, minus zero. The part has failed inspection.',
      position: 'center',
      route: '/inspection/1',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
    {
      id: 'fail-2',
      title: 'Creating an NCR',
      content: 'The system prompts the operator to create a Non-Conformance Report. The NCR is the formal document that records what went wrong, why it happened, and what will be done about it.',
      voiceover: 'The system prompts the operator to create a Non-Conformance Report. The NCR is the formal document that records what went wrong, why it happened, and what will be done about it.',
      target: 'a[href*=ncr], button',
      position: 'top',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'fail-3',
      title: 'Problem Description',
      content: 'The operator describes the defect: excessive porosity detected in the internal bore surface during final inspection. Pore clusters are visible at 3 and 9 o-clock positions.',
      voiceover: 'The operator describes the defect in detail: excessive porosity detected in the internal bore surface during final inspection. Pore clusters visible at three and nine o-clock positions.',
      target: 'textarea',
      position: 'top',
      route: '/ncr',
      waitForElement: 1000,
    },
    {
      id: 'fail-4',
      title: 'Part & Job Information',
      content: 'The NCR automatically captures the part number PN-PUMP-HOUSING-4402, job number FTQ-2026-0048, and material Cast Iron GG25. This links the quality issue directly to the production record.',
      voiceover: 'The NCR automatically captures the part number, job number, and material specification. This links the quality issue directly to the production record.',
      target: 'input',
      position: 'right',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'fail-5',
      title: 'Defect Classification',
      content: 'The defect type is selected: Porosity. The severity is recorded as Major. This classification helps quality teams prioritise investigations and track defect trends.',
      voiceover: 'The defect type is selected: Porosity. The severity is recorded as Major. This classification helps quality teams prioritise investigations and track defect trends.',
      target: 'select',
      position: 'right',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'fail-6',
      title: 'Root Cause Analysis',
      content: 'Using the 5-Why methodology, the team identifies the root cause: inadequate venting in the mold cavity during pouring, combined with excessive moisture in the sand mix.',
      voiceover: 'Using the five-why method, the team identifies the root cause: inadequate venting in the mold cavity during pouring, combined with excessive moisture in the sand mix.',
      target: 'textarea',
      position: 'top',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'fail-7',
      title: 'Corrective Action',
      content: 'Corrective actions are recorded: increase vent holes from 4 to 8, reduce sand moisture to 3.5%, add risers at the bore location, and re-inspect 100% of the next batch.',
      voiceover: 'Corrective actions are recorded: increase vent holes from four to eight, reduce sand moisture to three point five percent, add risers at the bore location, and re-inspect one hundred percent of the next batch.',
      target: 'textarea',
      position: 'top',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'fail-8',
      title: 'Financial Impact',
      content: 'The scrap cost is recorded: one thousand two hundred and forty dollars and fifty cents. Capturing financial impact helps management understand the true cost of quality issues.',
      voiceover: 'The scrap cost is recorded: one thousand two hundred and forty dollars and fifty cents. Capturing financial impact helps management understand the true cost of quality issues.',
      target: 'input[type=number]',
      position: 'right',
      route: '/ncr',
      waitForElement: 500,
    },
    {
      id: 'fail-9',
      title: 'NCR Submitted',
      content: 'The NCR is now in the system. It is visible to quality managers, production managers, and engineering. The status is OPEN and requires investigation.',
      voiceover: 'The NCR is now in the system. It is visible to quality managers, production managers, and engineering. The status is open and requires investigation.',
      position: 'center',
      route: '/ncr',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
