import type { TutorialTour } from '../types'

export const foundryTour: TutorialTour = {
  id: 'foundry',
  videoNumber: 6,
  title: 'Foundry NCR & AI Defect Analysis',
  subtitle: 'AI-Assisted Quality Analysis for Foundry Operations',
  description: 'Demonstrates the Foundry NCR workflow with AI-powered defect classification, severity assessment, and historical comparison.',
  estimatedDuration: '4:00',
  steps: [
    {
      id: 'foundry-1',
      title: 'Foundry Quality Control',
      content: 'In foundry operations, visual inspection of castings is critical. Defects like porosity, blow holes, shrinkage, and sand inclusions must be identified, classified, and tracked.',
      voiceover: 'In foundry operations, visual inspection of castings is critical. Defects like porosity, blow holes, shrinkage, and sand inclusions must be identified, classified, and tracked.',
      position: 'center',
      route: '/foundry-dashboard',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
    {
      id: 'foundry-2',
      title: 'Creating a Foundry NCR',
      content: 'When a casting defect is found, the operator creates a Foundry NCR. This captures the defect type, severity, batch number, and furnace ID for full traceability.',
      voiceover: 'When a casting defect is found, the operator creates a Foundry NCR. This captures the defect type, severity, batch number, and furnace ID for full traceability.',
      target: 'button',
      position: 'top',
      route: '/foundry-dashboard',
      waitForElement: 800,
    },
    {
      id: 'foundry-3',
      title: 'Defect Classification',
      content: 'The defect is classified as Porosity. The severity is Major. The batch number is BATCH-2026-048-A from Furnace 03. This information links the defect to the exact production conditions.',
      voiceover: 'The defect is classified as Porosity. The severity is Major. The batch number is BATCH-2026-048-A from Furnace Zero-Three. This links the defect to exact production conditions.',
      target: 'select',
      position: 'right',
      route: '/foundry-ncr',
      waitForElement: 1000,
    },
    {
      id: 'foundry-4',
      title: 'Photographic Evidence',
      content: 'The operator uploads photographs of the defect. These images become part of the permanent record and can be used for visual comparison with historical defects.',
      voiceover: 'The operator uploads photographs of the defect. These images become part of the permanent record and can be used for visual comparison with historical defects.',
      target: 'input[type=file]',
      position: 'top',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'foundry-5',
      title: 'AI Defect Analysis',
      content: 'ForgeTraceIQ analyses the uploaded image using AI vision. The system identifies the defect type, estimates severity, and provides a confidence score. This assists the quality team but does not replace professional engineering judgement.',
      voiceover: 'ForgeTraceIQ analyses the uploaded image using AI vision. The system identifies the defect type, estimates severity, and provides a confidence score. This assists the quality team but does not replace professional engineering judgement.',
      target: '[class*=ai]',
      position: 'left',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'foundry-6',
      title: 'AI Prediction Results',
      content: 'The AI predicts Porosity with 87% confidence. It also suggests a secondary possibility: Blow Hole at 14% confidence. The quality engineer reviews this and confirms the primary diagnosis.',
      voiceover: 'The AI predicts Porosity with eighty-seven percent confidence. It also suggests a secondary possibility: Blow Hole at fourteen percent. The quality engineer reviews this and confirms the diagnosis.',
      target: '[class*=prediction]',
      position: 'left',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'foundry-7',
      title: 'Historical Pattern',
      content: 'The system alerts the team that this is the fourth porosity NCR for Pump Housing. A pattern is emerging that demands engineering attention.',
      voiceover: 'The system alerts the team that this is the fourth porosity NCR for Pump Housing. A pattern is emerging that demands engineering attention.',
      target: '[class*=repeat]',
      position: 'right',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'foundry-8',
      title: 'Root Cause & Corrective Action',
      content: 'The root cause is recorded: inadequate venting and high sand moisture. The corrective action: increase vent holes, reduce moisture, add risers.',
      voiceover: 'The root cause is recorded: inadequate venting and high sand moisture. The corrective action: increase vent holes, reduce moisture, add risers.',
      target: 'textarea',
      position: 'top',
      route: '/foundry-ncr',
      waitForElement: 500,
    },
    {
      id: 'foundry-9',
      title: 'AI as an Assistant, Not a Replacement',
      content: 'It is important to understand that AI analysis assists the manufacturing and quality team. Final decisions always rest with qualified engineers and quality professionals.',
      voiceover: 'It is important to understand that AI analysis assists the manufacturing and quality team. Final decisions always rest with qualified engineers and quality professionals.',
      position: 'center',
      route: '/foundry-ncr',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
