import type { TutorialTour } from '../types'

export const inspectionTour: TutorialTour = {
  id: 'inspection',
  videoNumber: 4,
  title: 'Digital Inspection',
  subtitle: 'Capturing Quality Records at the Point of Manufacture',
  description: 'Demonstrates the complete inspection process: requirements, measurement entry, pass/fail determination, and digital quality record creation.',
  estimatedDuration: '3:30',
  steps: [
    {
      id: 'insp-1',
      title: 'Inspection Requirements',
      content: 'The inspection form shows all dimensions that must be checked: OD Diameter, Bore Diameter, Face Runout, Wall Thickness, and Overall Length. Each dimension has a nominal value and tolerance range.',
      voiceover: 'The inspection form shows all dimensions that must be checked. Each dimension has a nominal value and a defined tolerance range. The operator knows exactly what to measure and what is acceptable.',
      target: 'h1',
      position: 'bottom',
      route: '/inspection/1',
      waitForElement: 1000,
    },
    {
      id: 'insp-2',
      title: 'Entering Measurements',
      content: 'The operator enters measured values for each dimension. The system automatically compares each measurement against the tolerance and indicates Pass or Fail immediately.',
      voiceover: 'The operator enters measured values for each dimension. The system automatically compares each measurement against the tolerance and indicates Pass or Fail immediately.',
      target: 'input[type=number]',
      position: 'top',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'insp-3',
      title: 'Pass Condition',
      content: 'When a measurement is within tolerance, the system shows a clear green PASS indicator. This gives the operator immediate feedback that the dimension is acceptable.',
      voiceover: 'When a measurement is within tolerance, the system shows a clear green pass indicator. This gives the operator immediate feedback that the dimension is acceptable.',
      target: '[class*=pass]',
      position: 'right',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'insp-4',
      title: 'Fail Condition',
      content: 'When a measurement is out of tolerance, the system shows a red FAIL indicator. This triggers the requirement for additional documentation and potentially a Non-Conformance Report.',
      voiceover: 'When a measurement is out of tolerance, the system shows a red fail indicator. This triggers the requirement for additional documentation and potentially a Non-Conformance Report.',
      target: '[class*=fail]',
      position: 'right',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'insp-5',
      title: 'Comments & Notes',
      content: 'When a dimension fails, the operator can add comments explaining the finding. These comments become part of the permanent quality record and help investigators understand the issue later.',
      voiceover: 'When a dimension fails, the operator can add comments explaining the finding. These comments become part of the permanent quality record and help investigators understand the issue later.',
      target: 'textarea',
      position: 'top',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'insp-6',
      title: 'Submitting Results',
      content: 'The operator submits the inspection results. This creates a digital quality record that is permanently linked to the job, the operator, and the timestamp. No paper forms to file or lose.',
      voiceover: 'The operator submits the inspection results. This creates a digital quality record that is permanently linked to the job, the operator, and the timestamp. No paper forms to file or lose.',
      target: 'button[type=submit]',
      position: 'top',
      route: '/inspection/1',
      waitForElement: 500,
    },
    {
      id: 'insp-7',
      title: 'Digital Quality Record',
      content: 'The inspection record is now part of the job history. Management can view it, quality engineers can analyse it, and future operators can learn from it. This is how traceability is built.',
      voiceover: 'The inspection record is now part of the job history. Management can view it, quality engineers can analyse it, and future operators can learn from it. This is how traceability is built.',
      position: 'center',
      route: '/inspection/1',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
