import type { TutorialTour } from '../types'

export const introTour: TutorialTour = {
  id: 'intro',
  videoNumber: 1,
  title: 'ForgeTraceIQ Introduction',
  subtitle: 'Digital Manufacturing Traceability & Quality Intelligence Platform',
  description: 'A professional opening demonstration that explains what ForgeTraceIQ is, why it matters, and what the viewer will learn.',
  estimatedDuration: '2:30',
  steps: [
    {
      id: 'intro-1',
      title: 'Welcome to ForgeTraceIQ',
      content: 'ForgeTraceIQ is a digital manufacturing platform designed to bring production traceability, quality control, non-conformance management and manufacturing intelligence into one connected system.',
      voiceover: 'Welcome to ForgeTraceIQ, a digital manufacturing platform designed to bring production traceability, quality control, non-conformance management and manufacturing intelligence into one connected system.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
    {
      id: 'intro-2',
      title: 'The Manufacturing Challenge',
      content: 'Manufacturers face a common problem: critical production and quality information is scattered across paper forms, spreadsheets, and disconnected systems. This creates gaps in traceability and delays problem resolution.',
      voiceover: 'Manufacturers face a common problem: critical production and quality information is scattered across paper forms, spreadsheets, and disconnected systems. This creates gaps in traceability and delays problem resolution.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 7000,
    },
    {
      id: 'intro-3',
      title: 'What ForgeTraceIQ Does',
      content: 'ForgeTraceIQ digitises manufacturing workflows, reduces paperwork, improves traceability, captures quality information, manages NCRs, records defect evidence, analyses recurring problems, and provides management visibility.',
      voiceover: 'ForgeTraceIQ digitises manufacturing workflows, reduces paperwork, improves traceability, captures quality information, manages non-conformance reports, records defect evidence, analyses recurring problems, and provides management visibility.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 8000,
    },
    {
      id: 'intro-4',
      title: 'Building Historical Intelligence',
      content: 'Every job, inspection, and non-conformance is recorded. Over time, this builds a valuable knowledge base of manufacturing intelligence that helps prevent repeat problems and drives continuous improvement.',
      voiceover: 'Every job, inspection, and non-conformance is recorded. Over time, this builds a valuable knowledge base of manufacturing intelligence that helps prevent repeat problems and drives continuous improvement.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 7000,
    },
    {
      id: 'intro-5',
      title: 'What You Will Learn',
      content: 'In this tutorial, we will follow a complete manufacturing workflow from the creation of a job through production, inspection, non-conformance management, AI-assisted defect analysis, and final resolution.',
      voiceover: 'In this tutorial, we will follow a complete manufacturing workflow from the creation of a job through production, inspection, non-conformance management, and final resolution.',
      position: 'center',
      route: '/',
      autoAdvance: true,
      autoAdvanceDelay: 7000,
    },
  ],
};
