import type { TutorialTour } from '../types'

export const jobWorkflowTour: TutorialTour = {
  id: 'job-workflow',
  videoNumber: 2,
  title: 'Operator Login & Job Workflow',
  subtitle: 'Getting Started with Production Jobs',
  description: 'Demonstrates operator login, navigating to the Jobs screen, selecting a production job, viewing job information, and starting work.',
  estimatedDuration: '3:00',
  steps: [
    {
      id: 'jw-1',
      title: 'Operator Login',
      content: 'The operator begins by logging into ForgeTraceIQ. Each operator has a unique ID that ensures every action is traceable to the person who performed it.',
      voiceover: 'The operator begins by logging into ForgeTraceIQ. Each operator has a unique ID that ensures every action is traceable to the person who performed it. This is the foundation of manufacturing traceability.',
      target: 'input',
      position: 'bottom',
      route: '/',
      waitForElement: 800,
    },
    {
      id: 'jw-2',
      title: 'Jobs Dashboard',
      content: 'After login, the operator sees the Jobs screen. This shows all active production jobs with part numbers, materials, and current status. Jobs are organised by priority and due date.',
      voiceover: 'After login, the operator sees the Jobs screen. This shows all active production jobs with part numbers, materials, and current status. Jobs are organised by priority and due date.',
      target: '[class*=card]',
      position: 'right',
      route: '/job-entry',
      waitForElement: 800,
    },
    {
      id: 'jw-3',
      title: 'Selecting a Production Job',
      content: 'The operator selects job FTQ-2026-0048, a Pump Housing. This job requires machining a cast iron component to precise tolerances.',
      voiceover: 'The operator selects job FTQ-2026-0048, a Pump Housing. This job requires machining a cast iron component to precise tolerances. Selecting the job opens the complete job packet.',
      target: 'button',
      position: 'right',
      route: '/job-entry',
      waitForElement: 800,
    },
    {
      id: 'jw-4',
      title: 'Job Information',
      content: 'The job detail view shows all critical information: part number PN-PUMP-HOUSING-4402, material Cast Iron GG25, job number FTQ-2026-0048, revision Rev-C, and full setup instructions.',
      voiceover: 'The job detail view shows all critical information: the part number, material specification, job number, revision, and full setup instructions. Everything the operator needs is in one place.',
      target: 'h1',
      position: 'bottom',
      route: '/setup-sheet/1',
      waitForElement: 1000,
    },
    {
      id: 'jw-5',
      title: 'Traceability Starts Here',
      content: 'By logging in and selecting a job, every subsequent action is automatically linked to this operator and this job. This creates an unbroken chain of traceability.',
      voiceover: 'By logging in and selecting a job, every subsequent action is automatically linked to this operator and this job. This creates an unbroken chain of traceability from raw material through to finished part.',
      position: 'center',
      route: '/setup-sheet/1',
      autoAdvance: true,
      autoAdvanceDelay: 7000,
    },
  ],
};
