import type { TutorialTour } from '../types'

export const ncrStatusTour: TutorialTour = {
  id: 'ncr-status',
  videoNumber: 8,
  title: 'NCR Status Workflow',
  subtitle: 'Managing the Non-Conformance Lifecycle',
  description: 'Demonstrates the complete NCR lifecycle: Open, In Progress, and Resolved statuses, and how this gives management visibility.',
  estimatedDuration: '2:30',
  steps: [
    {
      id: 'status-1',
      title: 'NCR Status Tracking',
      content: 'Every NCR has a status that reflects where it is in the resolution process. This gives managers immediate visibility into the state of quality issues across the factory.',
      voiceover: 'Every NCR has a status that reflects where it is in the resolution process. This gives managers immediate visibility into the state of quality issues across the factory.',
      position: 'center',
      route: '/foundry-ncr-library',
      autoAdvance: true,
      autoAdvanceDelay: 5000,
    },
    {
      id: 'status-2',
      title: 'OPEN Status',
      content: 'When an NCR is first created, its status is OPEN. This means the issue has been identified and recorded, but investigation or corrective action has not yet begun.',
      voiceover: 'When an NCR is first created, its status is open. This means the issue has been identified and recorded, but investigation or corrective action has not yet begun.',
      target: '[class*=open]',
      position: 'right',
      route: '/foundry-ncr-library',
      waitForElement: 800,
    },
    {
      id: 'status-3',
      title: 'IN PROGRESS Status',
      content: 'When investigation begins, the status changes to IN PROGRESS. This tells everyone that the quality team is actively working on understanding the root cause and planning corrective actions.',
      voiceover: 'When investigation begins, the status changes to in progress. This tells everyone that the quality team is actively working on understanding the root cause and planning corrective actions.',
      target: '[class*=progress]',
      position: 'right',
      route: '/foundry-ncr-library',
      waitForElement: 500,
    },
    {
      id: 'status-4',
      title: 'RESOLVED Status',
      content: 'When corrective actions are completed and verified, the status becomes RESOLVED. The NCR remains in the system for historical analysis but is no longer an active issue.',
      voiceover: 'When corrective actions are completed and verified, the status becomes resolved. The NCR remains in the system for historical analysis but is no longer an active issue.',
      target: '[class*=resolved]',
      position: 'right',
      route: '/foundry-ncr-library',
      waitForElement: 500,
    },
    {
      id: 'status-5',
      title: 'Status Transitions',
      content: 'The operator or quality manager changes status using simple buttons: Mark Open, Mark In Progress, Mark Resolved. Each transition is logged with the user and timestamp.',
      voiceover: 'The operator or quality manager changes status using simple buttons. Each transition is logged with the user and timestamp for complete auditability.',
      target: 'button',
      position: 'top',
      route: '/foundry-ncr-library',
      waitForElement: 500,
    },
    {
      id: 'status-6',
      title: 'Management Visibility',
      content: 'By tracking status in real time, management knows exactly how many quality issues are open, which are being worked on, and which have been resolved. No more waiting for weekly reports.',
      voiceover: 'By tracking status in real time, management knows exactly how many quality issues are open, which are being worked on, and which have been resolved. No more waiting for weekly reports.',
      position: 'center',
      route: '/foundry-ncr-library',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
