import type { TutorialTour } from '../types'

export const setupSheetTour: TutorialTour = {
  id: 'setup-sheet',
  videoNumber: 3,
  title: 'Digital Setup Sheet',
  subtitle: 'Replacing Paper with Digital Work Instructions',
  description: 'Demonstrates how operators access digital setup instructions, machine information, tooling details, and process photographs.',
  estimatedDuration: '3:30',
  steps: [
    {
      id: 'ss-1',
      title: 'The Setup Sheet',
      content: 'The Digital Setup Sheet replaces traditional paper setup documentation. The operator can view all setup instructions, machine settings, tooling requirements, and workholding details in one place.',
      voiceover: 'The Digital Setup Sheet replaces traditional paper setup documentation. Instead of searching through files or multiple locations, the operator accesses everything from the digital workflow.',
      target: 'h1',
      position: 'bottom',
      route: '/setup-sheet/1',
      waitForElement: 1000,
    },
    {
      id: 'ss-2',
      title: 'Machine Information',
      content: 'The setup sheet specifies the machine: DMG Mori NLX-2500. It also shows spindle speed, feed rate, and coolant requirements. This ensures the operator configures the machine correctly before starting.',
      voiceover: 'The setup sheet specifies the machine: DMG Mori NLX-2500. It also shows spindle speed, feed rate, and coolant requirements. This ensures correct machine configuration before starting.',
      target: '[class*=machine]',
      position: 'right',
      route: '/setup-sheet/1',
      waitForElement: 500,
    },
    {
      id: 'ss-3',
      title: 'Tooling Details',
      content: 'Required tooling is listed: Sandvik Coromant CNMG 432 inserts, tool holder specification, and cutting parameters. The operator verifies each tool is available and in good condition before setup.',
      voiceover: 'Required tooling is listed with full specifications. The operator verifies each tool is available and in good condition before setup, preventing mid-job tool changes and quality issues.',
      target: '[class*=tool]',
      position: 'right',
      route: '/setup-sheet/1',
      waitForElement: 500,
    },
    {
      id: 'ss-4',
      title: 'Workholding & Fixtures',
      content: 'The workholding method is documented: 3-Jaw Power Chuck, 200mm. This ensures consistent setup and reduces variation between operators and shifts.',
      voiceover: 'The workholding method is documented: 3-Jaw Power Chuck, 200 millimetres. This ensures consistent setup and reduces variation between operators and shifts.',
      target: '[class*=hold]',
      position: 'right',
      route: '/setup-sheet/1',
      waitForElement: 500,
    },
    {
      id: 'ss-5',
      title: 'Setup Photographs',
      content: 'Setup photographs provide visual confirmation of correct workpiece orientation, fixture positioning, and tool clearance. Operators can also annotate photos to highlight critical areas.',
      voiceover: 'Setup photographs provide visual confirmation of correct workpiece orientation, fixture positioning, and tool clearance. Operators can also annotate photos to highlight critical areas.',
      target: 'img',
      position: 'top',
      route: '/setup-sheet/1',
      waitForElement: 500,
    },
    {
      id: 'ss-6',
      title: 'No More Paper',
      content: 'ForgeTraceIQ eliminates the need to search through paper files. Setup sheets are always current, always available, and permanently linked to the job record. This reduces setup time and prevents errors from outdated instructions.',
      voiceover: 'ForgeTraceIQ eliminates the need to search through paper files. Setup sheets are always current, always available, and permanently linked to the job record. This reduces setup time and prevents errors.',
      position: 'center',
      route: '/setup-sheet/1',
      autoAdvance: true,
      autoAdvanceDelay: 7000,
    },
  ],
};
