import type { TutorialTour } from '../types'

export const visualHistoryTour: TutorialTour = {
  id: 'visual-history',
  videoNumber: 7,
  title: 'Photographic Traceability',
  subtitle: 'Visual Evidence for Quality Records',
  description: 'Demonstrates how operators add photographs to NCRs, view visual history, and compare historical defect records.',
  estimatedDuration: '2:30',
  steps: [
    {
      id: 'vh-1',
      title: 'Visual Evidence',
      content: 'Photographs provide an additional layer of traceability. They allow the organisation to understand not only what defect was recorded, but also what the defect looked like.',
      voiceover: 'Photographs provide an additional layer of traceability. They allow the organisation to understand not only what defect was recorded, but also what the defect looked like.',
      position: 'center',
      route: '/visual-history',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
    {
      id: 'vh-2',
      title: 'Adding Photographs',
      content: 'The operator captures or uploads photographs directly from the NCR screen. Images are automatically linked to the NCR and become part of the permanent quality record.',
      voiceover: 'The operator captures or uploads photographs directly from the NCR screen. Images are automatically linked to the NCR and become part of the permanent quality record.',
      target: 'input[type=file]',
      position: 'top',
      route: '/visual-history',
      waitForElement: 800,
    },
    {
      id: 'vh-3',
      title: 'Viewing the Visual History',
      content: 'The Visual History page shows all photographs organised by date, part number, and defect type. Quality teams can browse through historical images to identify patterns.',
      voiceover: 'The Visual History page shows all photographs organised by date, part number, and defect type. Quality teams can browse through historical images to identify patterns.',
      target: '[class*=gallery]',
      position: 'right',
      route: '/visual-history',
      waitForElement: 500,
    },
    {
      id: 'vh-4',
      title: 'Comparing Defects',
      content: 'By comparing photographs from multiple NCRs, the quality team can see if the same type of defect is recurring. Similar pore patterns across different batches indicate a process issue.',
      voiceover: 'By comparing photographs from multiple NCRs, the quality team can see if the same type of defect is recurring. Similar pore patterns across different batches indicate a process issue.',
      target: '[class*=compare]',
      position: 'right',
      route: '/visual-history',
      waitForElement: 500,
    },
    {
      id: 'vh-5',
      title: 'Permanent Visual Record',
      content: 'Unlike paper reports that can be lost or damaged, digital photographs are permanently stored, searchable, and always available for review, audit, or training purposes.',
      voiceover: 'Unlike paper reports that can be lost or damaged, digital photographs are permanently stored, searchable, and always available for review, audit, or training purposes.',
      position: 'center',
      route: '/visual-history',
      autoAdvance: true,
      autoAdvanceDelay: 6000,
    },
  ],
};
