import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/providers/trpc";
import { isDemoMode, demoApi } from "@/lib/demoApi";
import {
  ArrowLeft,
  Play,
  Download,
  Save,
  Loader2,
  AlertTriangle,
  CheckCircle2,
  Lightbulb,
  Brain,
  Settings,
  Code,
  Shield,
  TrendingUp,
} from "lucide-react";

const OPERATION_TYPES = [
  { value: "facing", label: "Facing" },
  { value: "od_turning", label: "OD Turning" },
  { value: "id_turning", label: "ID Turning" },
  { value: "drilling", label: "Drilling" },
];

const MATERIALS = [
  "AL-6061",
  "AL-7075",
  "SS-303",
  "SS-316",
  "TI-64",
  "IN-718",
  "MS-360",
  "ST-1018",
];

interface ValidationError {
  field: string;
  message: string;
}

export default function CNCProgram() {
  const navigate = useNavigate();
  const [operator, setOperator] = useState<{ id: number; name: string } | null>(null);

  // Form state
  const [programType, setProgramType] = useState("");
  const [diameter, setDiameter] = useState("");
  const [length, setLength] = useState("");
  const [material, setMaterial] = useState("");
  const [tool, setTool] = useState("");
  const [feed, setFeed] = useState("");
  const [speed, setSpeed] = useState("");

  // Result state
  const [gcode, setGcode] = useState("");
  const [toolWarning, setToolWarning] = useState<string | null>(null);
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const [savedProgramId, setSavedProgramId] = useState<number | null>(null);

  // Demo mode state for optimizations
  const [demoOptimized, setDemoOptimized] = useState<{
    hasData: boolean;
    passRate: number;
    totalRuns: number;
    byProgramType: any[];
    recentAdjustments: any[];
  } | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem("cnc_operator");
    if (!saved) {
      navigate("/");
      return;
    }
    try {
      setOperator(JSON.parse(saved));
    } catch {
      navigate("/");
    }
  }, [navigate]);

  // Load demo optimized settings when in demo mode
  useEffect(() => {
    if (isDemoMode() && material.length > 0) {
      const opt = demoApi.getOptimizedSettings(material);
      setDemoOptimized(opt);
    }
  }, [material]);

  // AI suggestion based on material + operation
  const aiSuggestion = trpc.cncProgram.getAiSuggestion.useQuery(
    {
      material: material || "x",
      operation: (programType as "facing" | "od_turning" | "id_turning" | "drilling") || "facing",
    },
    { enabled: material.length > 0 && programType.length > 0 && !isDemoMode() }
  );

  // Optimization: feedback-based settings from previous successful runs
  const optimizedSettings = trpc.feedback.getOptimizedSettings.useQuery(
    { partNumber: material || "x" },
    { enabled: material.length > 0 && !isDemoMode() }
  );

  // Local gcode generator for demo mode
  function generateLocalGcode(params: {
    programType: string;
    diameter: number;
    length: number;
    material: string;
    tool: string;
    feed: number;
    speed: number;
  }) {
    const { programType, diameter, length, material, tool, feed, speed } = params;
    const lines: string[] = [];
    lines.push("%");
    lines.push(`O${Math.floor(Math.random() * 9000 + 1000)} (${programType.toUpperCase()}_${material})`);
    lines.push("(GENERATED BY CNC SHOP FLOOR DIGITIZATION - DEMO MODE)");
    lines.push("N10 G21 G40 G80 G99");
    lines.push("N20 G28 U0 W0");
    lines.push(`N30 T${tool} M6`);
    lines.push(`N40 G96 S${speed} M3`);
    lines.push(`N50 G50 S${Math.round(speed * 1.2)}`);
    lines.push("N60 G00 X0 Z0.5");
    
    if (programType === "facing") {
      lines.push(`N70 G01 X${(diameter + 2).toFixed(2)} Z0 F${feed.toFixed(3)}`);
      lines.push(`N80 G01 X${(diameter + 2).toFixed(2)} Z-${(length * 0.1).toFixed(2)}`);
      lines.push("N90 G00 X0 Z0.5");
    } else if (programType === "od_turning") {
      lines.push(`N70 G01 X${diameter.toFixed(2)} Z0 F${feed.toFixed(3)}`);
      lines.push(`N80 G01 X${diameter.toFixed(2)} Z-${length.toFixed(2)}`);
      lines.push(`N90 G01 X${(diameter + 2).toFixed(2)} Z-${length.toFixed(2)}`);
      lines.push("N100 G00 X0 Z0.5");
    } else if (programType === "id_turning") {
      const id = Math.max(diameter - 10, 5);
      lines.push(`N70 G01 X${id.toFixed(2)} Z0 F${feed.toFixed(3)}`);
      lines.push(`N80 G01 X${id.toFixed(2)} Z-${length.toFixed(2)}`);
      lines.push(`N90 G01 X${(id - 2).toFixed(2)} Z-${length.toFixed(2)}`);
      lines.push("N100 G00 X0 Z0.5");
    } else if (programType === "drilling") {
      lines.push(`N70 G83 X0 Z0 R0.5 Q${(length / 5).toFixed(2)} F${feed.toFixed(3)} P200`);
      lines.push(`N80 G80 Z-${length.toFixed(2)}`);
      lines.push("N90 G00 X0 Z0.5");
    }
    
    lines.push("N200 G28 U0 W0");
    lines.push("N210 M30");
    lines.push("%");
    
    return {
      gcode: lines.join("\n"),
      toolWarning: null,
    };
  }

  const generateProgram = trpc.cncProgram.generate.useMutation({
    onSuccess: (data) => {
      setGcode(data.gcode);
      setToolWarning(data.toolWarning);
      setValidationErrors([]);
      setError("");
      setSaved(false);
    },
    onError: (err) => {
      setError(err.message);
      setGcode("");
    },
  });

  const saveProgram = trpc.cncProgram.save.useMutation({
    onSuccess: (data) => {
      setSaved(true);
      setSavedProgramId(data.programId);
      setError("");
    },
    onError: () => {
      if (isDemoMode() && operator && gcode) {
        const result = demoApi.saveProgram({
          operatorId: operator.id,
          programType: programType as "facing" | "od_turning" | "id_turning" | "drilling",
          parameters: JSON.stringify({ programType, diameter, length, material, tool, feed, speed }),
          gcodeText: gcode,
        });
        setSaved(true);
        setSavedProgramId(result.programId);
        setError("");
        return;
      }
      setError("Failed to save program.");
    },
  });

  function validate(): ValidationError[] {
    const errors: ValidationError[] = [];
    if (!programType) errors.push({ field: "type", message: "Operation type is required" });
    if (!diameter || isNaN(parseFloat(diameter)) || parseFloat(diameter) <= 0) {
      errors.push({ field: "diameter", message: "Diameter must be a positive number" });
    }
    if (!length || isNaN(parseFloat(length)) || parseFloat(length) <= 0) {
      errors.push({ field: "length", message: "Length must be a positive number" });
    }
    if (!material) errors.push({ field: "material", message: "Material is required" });
    if (!tool.trim()) errors.push({ field: "tool", message: "Tool number is required" });
    if (!feed || isNaN(parseFloat(feed))) {
      errors.push({ field: "feed", message: "Feed rate is required" });
    } else {
      const f = parseFloat(feed);
      if (f < 0.05 || f > 2.0) errors.push({ field: "feed", message: "Feed must be between 0.05 and 2.0" });
    }
    if (!speed || isNaN(parseFloat(speed))) {
      errors.push({ field: "speed", message: "Spindle speed is required" });
    } else {
      const s = parseFloat(speed);
      if (s < 100 || s > 5000) errors.push({ field: "speed", message: "Speed must be between 100 and 5000 RPM" });
    }
    return errors;
  }

  const handleGenerate = () => {
    setError("");
    setSaved(false);
    const errors = validate();
    if (errors.length > 0) {
      setValidationErrors(errors);
      return;
    }
    setValidationErrors([]);

    if (isDemoMode()) {
      const result = generateLocalGcode({
        programType: programType as "facing" | "od_turning" | "id_turning" | "drilling",
        diameter: parseFloat(diameter),
        length: parseFloat(length),
        material,
        tool,
        feed: parseFloat(feed),
        speed: parseFloat(speed),
      });
      setGcode(result.gcode);
      setToolWarning(result.toolWarning);
      setError("");
      setSaved(false);
      return;
    }

    generateProgram.mutate({
      programType: programType as "facing" | "od_turning" | "id_turning" | "drilling",
      diameter: parseFloat(diameter),
      length: parseFloat(length),
      material,
      tool,
      feed: parseFloat(feed),
      speed: parseFloat(speed),
    });
  };

  const handleSave = () => {
    if (!operator || !gcode) return;
    const params = JSON.stringify({ programType, diameter, length, material, tool, feed, speed });
    saveProgram.mutate({
      operatorId: operator.id,
      programType: programType as "facing" | "od_turning" | "id_turning" | "drilling",
      parameters: params,
      gcodeText: gcode,
    });
  };

  const handleDownload = () => {
    if (!gcode) return;
    const blob = new Blob([gcode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `CNC_${programType}_${Date.now()}.nc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  function getFieldError(field: string): string | undefined {
    return validationErrors.find((e) => e.field === field)?.message;
  }

  const suggestion = aiSuggestion.data;
  const optData = isDemoMode() ? demoOptimized : optimizedSettings.data;

  return (
    <div className="min-h-screen bg-slate-50 p-4">
      <div className="mx-auto max-w-5xl">
        {/* Header */}
        <div className="mb-4 flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="lg"
              className="h-12 px-4 text-base font-semibold"
              onClick={() => navigate("/job-entry")}
            >
              <ArrowLeft className="mr-2 h-5 w-5" />
              Back
            </Button>
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-slate-900">
                <Code className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-slate-900">
                  CNC Program Generator
                </h1>
                <p className="text-sm text-slate-500">
                  Template-based, safety-validated G-code
                </p>
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="lg"
            className="h-12 px-4 text-base font-semibold"
            onClick={() => navigate("/dashboard")}
          >
            <Settings className="mr-2 h-5 w-5" />
            Dashboard
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {/* LEFT: Input Form */}
          <div className="space-y-4">
            {/* Validation Summary */}
            {validationErrors.length > 0 && (
              <Card className="border-red-300 bg-red-50 shadow-sm">
                <CardContent className="py-3">
                  <div className="flex items-start gap-2">
                    <Shield className="h-5 w-5 text-red-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="text-sm font-bold text-red-700">
                        Please fix the following errors:
                      </p>
                      <ul className="text-sm text-red-600 mt-1 space-y-1">
                        {validationErrors.map((e, i) => (
                          <li key={i}>• {e.message}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Program Form */}
            <Card className="shadow-md border-slate-200">
              <CardHeader className="pb-3">
                <CardTitle className="text-xl flex items-center gap-2">
                  <Settings className="h-5 w-5 text-slate-700" />
                  Program Parameters
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Operation Type */}
                <div className="space-y-2">
                  <Label className="text-base font-semibold">
                    Operation Type <span className="text-red-500">*</span>
                  </Label>
                  <Select value={programType} onValueChange={setProgramType}>
                    <SelectTrigger className="h-14 text-base">
                      <SelectValue placeholder="Select operation..." />
                    </SelectTrigger>
                    <SelectContent>
                      {OPERATION_TYPES.map((op) => (
                        <SelectItem key={op.value} value={op.value}>
                          {op.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {getFieldError("type") && (
                    <p className="text-xs text-red-600">{getFieldError("type")}</p>
                  )}
                </div>

                {/* Diameter & Length */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-base font-semibold">
                      Diameter (mm) <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={diameter}
                      onChange={(e) => setDiameter(e.target.value)}
                      placeholder="e.g. 50.0"
                      className={`h-12 text-base ${getFieldError("diameter") ? "border-red-400" : ""}`}
                    />
                    {getFieldError("diameter") && (
                      <p className="text-xs text-red-600">{getFieldError("diameter")}</p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Label className="text-base font-semibold">
                      {programType === "drilling" ? "Depth (mm)" : "Length (mm)"}{" "}
                      <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="number"
                      step="0.01"
                      value={length}
                      onChange={(e) => setLength(e.target.value)}
                      placeholder="e.g. 25.0"
                      className={`h-12 text-base ${getFieldError("length") ? "border-red-400" : ""}`}
                    />
                    {getFieldError("length") && (
                      <p className="text-xs text-red-600">{getFieldError("length")}</p>
                    )}
                  </div>
                </div>

                {/* Material */}
                <div className="space-y-2">
                  <Label className="text-base font-semibold">
                    Material <span className="text-red-500">*</span>
                  </Label>
                  <Select value={material} onValueChange={setMaterial}>
                    <SelectTrigger className="h-12 text-base">
                      <SelectValue placeholder="Select material..." />
                    </SelectTrigger>
                    <SelectContent>
                      {MATERIALS.map((m) => (
                        <SelectItem key={m} value={m}>
                          {m}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {getFieldError("material") && (
                    <p className="text-xs text-red-600">{getFieldError("material")}</p>
                  )}
                </div>

                {/* Tool */}
                <div className="space-y-2">
                  <Label className="text-base font-semibold">
                    Tool Number <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    value={tool}
                    onChange={(e) => setTool(e.target.value)}
                    placeholder="e.g. 0101 or T01"
                    className={`h-12 text-base ${getFieldError("tool") ? "border-red-400" : ""}`}
                  />
                  {getFieldError("tool") && (
                    <p className="text-xs text-red-600">{getFieldError("tool")}</p>
                  )}
                </div>

                {/* Feed & Speed */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-base font-semibold">
                      Feed Rate <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="number"
                      step="0.001"
                      value={feed}
                      onChange={(e) => setFeed(e.target.value)}
                      placeholder="0.05 - 2.0"
                      className={`h-12 text-base ${getFieldError("feed") ? "border-red-400" : ""}`}
                    />
                    {getFieldError("feed") && (
                      <p className="text-xs text-red-600">{getFieldError("feed")}</p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Label className="text-base font-semibold">
                      Spindle Speed (RPM) <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="number"
                      step="10"
                      value={speed}
                      onChange={(e) => setSpeed(e.target.value)}
                      placeholder="100 - 5000"
                      className={`h-12 text-base ${getFieldError("speed") ? "border-red-400" : ""}`}
                    />
                    {getFieldError("speed") && (
                      <p className="text-xs text-red-600">{getFieldError("speed")}</p>
                    )}
                  </div>
                </div>

                {/* AI Suggestion */}
                {suggestion && (
                  <Card className="border-blue-200 bg-blue-50 shadow-sm">
                    <CardContent className="py-3">
                      <div className="flex items-start gap-2">
                        <Brain className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                        <div>
                          <p className="text-sm font-bold text-blue-800">
                            AI Recommendation for {material}
                          </p>
                          <p className="text-sm text-blue-700 mt-1">
                            Feed: <strong>{suggestion.feed}</strong> mm/rev · Speed:{" "}
                            <strong>{suggestion.speed}</strong> RPM
                          </p>
                          <p className="text-xs text-blue-600 mt-1 flex items-center gap-1">
                            <Lightbulb className="h-3 w-3" />
                            {suggestion.note}
                          </p>
                          <div className="flex gap-2 mt-2">
                            <Button
                              variant="outline"
                              size="sm"
                              className="text-xs h-8"
                              onClick={() => setFeed(String(suggestion.feed))}
                            >
                              Apply Feed
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              className="text-xs h-8"
                              onClick={() => setSpeed(String(suggestion.speed))}
                            >
                              Apply Speed
                            </Button>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Optimization: Feedback-based settings */}
                {optData?.hasData && (
                  <Card className="border-emerald-200 bg-emerald-50 shadow-sm">
                    <CardContent className="py-3">
                      <div className="flex items-start gap-2">
                        <TrendingUp className="h-5 w-5 text-emerald-600 mt-0.5 flex-shrink-0" />
                        <div className="w-full">
                          <div className="flex items-center gap-2">
                            <p className="text-sm font-bold text-emerald-800">
                              Optimized from {optData.passRate}% success rate
                            </p>
                            <span className="text-xs text-emerald-500">
                              ({optData.totalRuns} runs)
                            </span>
                          </div>
                          {optData.byProgramType
                            .filter((p) => p.programType === programType)
                            .map((prog, i) => (
                              <div key={i} className="mt-2 space-y-1">
                                {prog.avgFeedAdjustment != null && (
                                  <p className="text-xs text-emerald-700">
                                    Avg feed override: <strong>{prog.avgFeedAdjustment}%</strong>
                                  </p>
                                )}
                                {prog.avgSpeedAdjustment != null && (
                                  <p className="text-xs text-emerald-700">
                                    Avg speed override: <strong>{prog.avgSpeedAdjustment}%</strong>
                                  </p>
                                )}
                                {prog.toolChangeRate > 0 && (
                                  <p className="text-xs text-amber-700">
                                    Tool change rate: <strong>{prog.toolChangeRate}%</strong> of runs
                                  </p>
                                )}
                              </div>
                            ))}
                          {optData.byProgramType.length > 0 && (
                            <div className="flex gap-2 mt-2">
                              {optData.byProgramType[0]?.avgFeedAdjustment != null && (
                                <Button
                                  variant="outline"
                                  size="sm"
                                  className="text-xs h-8 border-emerald-300"
                                  onClick={() => {
                                    const baseFeed = parseFloat(feed) || suggestion?.feed || 0.15;
                                    const adj = optData!.byProgramType[0].avgFeedAdjustment!;
                                    setFeed((baseFeed * (1 + adj / 100)).toFixed(4));
                                  }}
                                >
                                  Apply Optimized Feed
                                </Button>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Tool Warning */}
                {toolWarning && (
                  <div className="rounded-md bg-amber-50 p-3 text-amber-800 text-sm font-medium flex items-start gap-2 border border-amber-200">
                    <AlertTriangle className="h-5 w-5 flex-shrink-0" />
                    {toolWarning}
                  </div>
                )}

                {/* Error */}
                {error && (
                  <div className="rounded-md bg-red-50 p-3 text-red-700 text-sm font-medium flex items-start gap-2">
                    <AlertTriangle className="h-5 w-5 flex-shrink-0" />
                    {error}
                  </div>
                )}

                {/* Generate Button */}
                <Button
                  className="w-full h-14 text-xl font-bold bg-slate-900 hover:bg-slate-800"
                  onClick={handleGenerate}
                  disabled={generateProgram.isPending}
                >
                  {generateProgram.isPending ? (
                    <>
                      <Loader2 className="mr-2 h-6 w-6 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Play className="mr-2 h-6 w-6" />
                      Generate G-Code
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* RIGHT: G-Code Preview */}
          <div className="space-y-4">
            {gcode ? (
              <>
                <Card className="shadow-md border-slate-200">
                  <CardHeader className="pb-2 flex flex-row items-center justify-between">
                    <CardTitle className="text-lg flex items-center gap-2">
                      <Code className="h-5 w-5 text-emerald-600" />
                      G-Code Preview
                    </CardTitle>
                    <span className="text-xs text-slate-400 font-mono">
                      {gcode.split("\n").length} lines
                    </span>
                  </CardHeader>
                  <CardContent>
                    <div className="bg-slate-900 rounded-lg p-4 overflow-x-auto max-h-[400px] overflow-y-auto">
                      <pre className="text-sm font-mono text-emerald-400 whitespace-pre">
                        {gcode}
                      </pre>
                    </div>
                  </CardContent>
                </Card>

                {/* Action Buttons */}
                <div className="grid grid-cols-2 gap-3">
                  <Button
                    variant="outline"
                    className="h-14 text-base font-semibold border-emerald-300 hover:bg-emerald-50"
                    onClick={handleDownload}
                  >
                    <Download className="mr-2 h-5 w-5" />
                    Download .NC
                  </Button>
                  <Button
                    className="h-14 text-base font-bold bg-emerald-600 hover:bg-emerald-700"
                    onClick={handleSave}
                    disabled={saveProgram.isPending || !operator}
                  >
                    {saveProgram.isPending ? (
                      <>
                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                        Saving...
                      </>
                    ) : (
                      <>
                        <Save className="mr-2 h-5 w-5" />
                        Confirm & Save
                      </>
                    )}
                  </Button>
                </div>

                {saved && (
                  <div className="rounded-md bg-emerald-50 p-3 text-emerald-700 text-sm font-medium flex items-center gap-2 border border-emerald-200">
                    <CheckCircle2 className="h-5 w-5" />
                    Program saved successfully! ID: {savedProgramId}
                  </div>
                )}
              </>
            ) : (
              <Card className="shadow-md border-slate-200 border-dashed">
                <CardContent className="py-16 text-center">
                  <Code className="h-12 w-12 text-slate-300 mx-auto mb-3" />
                  <p className="text-lg text-slate-500 font-medium">
                    No G-code generated yet
                  </p>
                  <p className="text-sm text-slate-400 mt-1">
                    Fill in the parameters and click Generate
                  </p>
                </CardContent>
              </Card>
            )}

            {/* Safety Notice */}
            <Card className="shadow-sm border-slate-200">
              <CardContent className="py-3 flex items-start gap-2">
                <Shield className="h-5 w-5 text-slate-500 mt-0.5 flex-shrink-0" />
                <div className="text-xs text-slate-500">
                  <p className="font-semibold">Safety Validation</p>
                  <p>
                    Feed: 0.05–2.0 mm/rev · Speed: 100–5000 RPM · All
                    parameters are range-checked before generation. Always verify
                    G-code in a simulator before running on machine.
                  </p>
                </div>
              </CardContent>
            </Card>
          
          </div>
        </div>
      </div>
    </div>
  );
}
